.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. llamacoin_qt test_llamacoin_qt
clean: FORCE
	$(MAKE) -C .. llamacoin_qt_clean test_llamacoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_llamacoin_qt_check
llamacoin-qt llamacoin-qt.exe: FORCE
	 $(MAKE) -C .. llamacoin_qt
